DROP DATABASE ID EXIST TESTE;
CREAT DATABASE TESTE;

USE TESTE;

CREATE TABLE aluno(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100),
  email VARCHAR(100)
);

CREATE TABLE aluno(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  alunoid INTEGER,
  cursos VARCHAR(100),
  data matricula DATE,
  FOREIGN KEY (alunoid) REFERENCES aluno(id)
);